# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
title: GYSR documentation
email: team@gysr.io
description: Documentation for GYSR v2 core contracts
baseurl: ""
url: ""
twitter_username: gysr_io
github_username: gysr-io

# Build settings
theme: minima

# Categories
categories: [contract]
